import { CheckCircle2, ClipboardList, MessageCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { publishCartMessage } from "@/lib/utils";
import { WA_PUBLISH, buildWAUrl } from "@/config/whatsapp";

function Text({ en, ta }: { en: string; ta: string }) {
  return (
    <>
      <span className="en">{en}</span>
      <span className="ta tamil-text">{ta}</span>
    </>
  );
}

const details = [
  ["Your Name", "உங்கள் பெயர்"],
  ["Phone Number", "தொலைபேசி எண்"],
  ["Number of Carts Available", "எத்தனை வண்டிகள் உள்ளன"],
  ["Cart Type (with stove / without stove / with top / etc.)", "வண்டி வகை (அடுப்பு / மேல் கவர் / அடுப்பு இல்லாதது)"],
  ["Rental Price You Expect (per day)", "எதிர்பார்க்கும் ஒரு நாள் வாடகை விலை"],
  ["Location in Coimbatore", "கோவையில் உங்கள் பகுதி"],
  ["Cart Photos (send on WhatsApp)", "வண்டி படங்கள் (வாட்ஸ்அப்பில் அனுப்பவும்)"]
];

const benefits = [
  ["Reach more rental customers", "அதிக வாடகை வாடிக்கையாளர்களை அடையுங்கள்"],
  ["Earn from idle carts", "பயன்படாத வண்டிகள் மூலம் வருமானம் ஈட்டுங்கள்"],
  ["Get listed in a premium marketplace", "பிரீமியம் சந்தையில் உங்கள் வண்டியை பதிவு செய்யுங்கள்"],
  ["Agree platform fee before listing", "பதிவு செய்வதற்கு முன் கட்டணத்தை ஒப்புக்கொள்ளுங்கள்"]
];

export default function PublishPage() {
  return (
    <main className="bg-[#F8F6F2] pt-16 md:pt-28">
      {/* Dynamic SEO Meta Tags are generated by metadata config in layout/page metadata */}
      <section className="pb-20 pt-24 md:pb-24 md:pt-0">
        <div className="site-container grid gap-6 md:grid-cols-[0.95fr_1.05fr] md:gap-6">
          <div className="flex flex-col justify-between">
            <div>
              <p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">
                <Text en="Vendor Network" ta="வண்டி உரிமையாளர் நெட்வொர்க்" />
              </p>
              <h1 className="mt-3 font-display text-5xl uppercase leading-none text-ink md:text-7xl">
                <Text en="Publish Your Cart on Thalluvandi" ta="என் வண்டி சேர்க்க" />
              </h1>
              <p className="mt-6 max-w-[680px] text-lg leading-8 text-muted">
                <Text en="If you own a food cart and want more rental customers, publish it on Thalluvandi." ta="உங்களுக்கு தள்ளுவண்டி இருந்தால் தள்ளுவண்டி தளத்தில் உங்கள் வண்டியை பதிவு செய்யுங்கள் — வாடிக்கையாளர்களை நாங்க தர்றோம்!" />
              </p>
            </div>
            <Button asChild size="lg" className="mt-8 bg-[#25D366] hover:bg-[#20ba5a] text-white">
              <a href={buildWAUrl(WA_PUBLISH, publishCartMessage)} target="_blank">
                <MessageCircle size={18} /> <Text en="📋 List My Cart" ta="📋 என் வண்டி சேர்க்க" />
              </a>
            </Button>
          </div>

          <div className="rounded-2xl border border-black/10 bg-white p-6 shadow-premium md:p-8">
            <h2 className="font-display text-5xl uppercase leading-none text-ink">
              <Text en="To list your cart, share these details on WhatsApp:" ta="பதிவு செய்ய இந்த விவரங்களை வாட்ஸ்அப்பில் பகிரவும்:" />
            </h2>
            <div className="mt-8 grid gap-3">
              {details.map(([detail, tamil]) => (
                <div key={detail} className="flex items-start gap-3 rounded-xl border border-black/10 bg-[#F8F6F2] p-4 text-left font-bold text-ink">
                  <ClipboardList className="mt-0.5 shrink-0 text-primary animate-pulse" />
                  <span>
                    <Text en={detail} ta={tamil} />
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      <section className="pb-24">
        <div className="site-container">
          <div className="rounded-2xl border border-black/10 bg-white p-6 md:p-8">
            <h2 className="font-display text-5xl uppercase leading-none text-ink">
              <Text en="Why publish?" ta="ஏன் பதிவு செய்ய வேண்டும்?" />
            </h2>
            <div className="mt-8 grid gap-4 md:grid-cols-2 md:gap-6">
              {benefits.map(([benefit, tamil]) => (
                <div key={benefit} className="flex min-h-14 items-center gap-3 rounded-xl border border-black/10 bg-[#F8F6F2] p-4 text-left font-bold text-ink">
                  <CheckCircle2 className="shrink-0 text-primary" />
                  <Text en={benefit} ta={tamil} />
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
